<?php
declare(strict_types=1);

namespace Source;

use PHPUnit\Util\Exception;

class Product
{
    private ?int $id = null;
    private string $name;
    private float $price;
    private int $quantity;
    private float $total;

    /**
     * @return int
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @param string $name
     * @return Product
     */
    public function setName(string $name): Product
    {
        $this->name = $name;
        return $this;
    }

    /**
     * @return float
     */
    public function getPrice(): float
    {
        return $this->price;
    }

    /**
     * @param float $price
     * @return Product
     */
    public function setPrice(float $price): Product
    {
        $this->price = $price;
        return $this;
    }

    /**
     * @return int
     */
    public function getQuantity(): int
    {
        return $this->quantity;
    }

    /**
     * @param int $quantity
     * @return Product
     */
    public function setQuantity(int $quantity): Product
    {
        $this->quantity = $quantity;
        return $this;
    }

    /**
     * @return float
     */
    public function getTotal(): float
    {
        return $this->total;
    }

    /**
     * @param float $total
     * @return Product
     */
    public function setTotal(float $total): Product
    {
        $this->total = $total;
        return $this;
    }

    /**
     * @throws \Exception
     */
    public function exception(): \Exception
    {
        throw new \Exception('Test Exception');
    }
}
